# Use the official Python image as a base image
FROM python:3.12

# Set the working directory in the container
WORKDIR /app

# Copy the dependencies file to the working directory
COPY requirements.txt .

# Install Flask and other dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the Flask application code into the container at /app
COPY . /app

# Expose port 5000 to allow communication to the Flask application
EXPOSE 5000

# Command to run the Flask application
CMD ["python", "app.py"]
